import './util/module-alias';
import { Server } from '@overnightjs/core';
import { Application } from 'express';
import bodyParser from 'body-parser';
import * as http from 'http';
import expressPino from 'express-pino-logger';
import cors from 'cors';
import swaggerUi from 'swagger-ui-express';
import { OpenApiValidator } from 'express-openapi-validatior';
import { OpenAPIV3 } from 'express-openapi-validator/dist/framework/type';
import { ForecastController } from './controllers/forecase';
import * as database from '@src/database';
